version: '3.4'

services:
  hrworkflowapi:
    image: hrworkflowapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    command: [ 'npm', 'run', 'dev' ]
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
  hrworkflowapi-mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    command: mongod --quiet --logpath /dev/null

volumes:
  data:
