version: '3.4'

services:
  hrworkflowapi-test:
    image: hrworkflowapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://hrworkflowdb:27017/hrworkflowdb
    command: [ 'npm', 'test' ]
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    links:
      - hrworkflowdb
  hrworkflowapi:
    image: hrworkflowapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://hrworkflowdb:27017/hrworkflowdb
    command: [ 'npm', 'run', 'dev' ]
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    links:
      - hrworkflowdb
  hrworkflowdb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - hrworkflow-data:/data/db
    command: mongod --quiet --logpath /dev/null

volumes:
  hrworkflow-data:
