version: '3.4'

services:
  hrworkflowapi:
    image: hrworkflowapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    command: [ 'npm', 'test' ]
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app